const ShoppingCartConstants = {
  SHOPPING_CART_PRODUCT_QUANTITY_CHANGED: 'SHOPPING_CART_PRODUCT_QUANTITY_CHANGED',
  SHOPPING_CART_PRODUCT_REMOVED: 'SHOPPING_CART_PRODUCT_REMOVED'
};

export default ShoppingCartConstants;
