var ShoppingCartConstants = {
    SHOPPING_CART_PRODUCT_QUANTITY_CHANGED: 'SHOPPING_CART_PRODUCT_QUANTITY_CHANGED',
    SHOPPING_CART_PRODUCT_REMOVED: 'SHOPPING_CART_PRODUCT_REMOVED'
};

module.exports = ShoppingCartConstants;